### ISSUE TITLE
Incompatible with 'tint.nvim': color resets when changing focused window

### ISSUE THREAD

**Issue by fnune** [rachartier/tiny-devicons-auto-colors.nvim#1]
Hi! Thanks for your plugin. I'm seeing the following issue:

The highlights work correctly when loading for the first time.

![image](https://github.com/rachartier/tiny-devicons-auto-colors.nvim/assets/16181067/98ac8e69-5be8-4df6-b539-9bcbc531fb35)

But when changing focus to another window and then coming back, the highlights revert to what they were without this plugin:

[Screencast from 2024-05-20 13-08-35.webm](https://github.com/rachartier/tiny-devicons-auto-colors.nvim/assets/16181067/f062ac5c-a680-4ae0-b450-326f52f60268)

If I disable `tint.nvim`, things work again! https://github.com/levouh/tint.nvim

I'm aware that supporting compatibility with other plugins may be out of scope for this project, but just wanted to notify you at least.

**Comment by rachartier** [comment]
Thanks for the feedback!

I'll take a look.

**Comment by rachartier** [comment]
I can't seem to reproduce this bug :( 

Looking at tint.nvim source code, it seems that the plugin save the state of all highlight. ([here](https://github.com/levouh/tint.nvim/blob/master/lua/tint.lua#L166)).

I'm thinking that maybe you have a loading priority problem?

You may need to load tiny-devicons-auto-colors.nvim before you're loading tint.nvim, so that tint.nvim can register the modified highlight group ?

After looking at the docs:
![image](https://github.com/rachartier/tiny-devicons-auto-colors.nvim/assets/2057541/6a41af17-d212-46a6-a913-99b20bbec112)

It seems that you can also call `require("tint").refresh()` after setup tiny-devicons-auto-colors.nvim. If you can try to add this in your config?

**Comment by fnune** [comment]
You're right! Fixed by adding priorities to my plugins (I'm using lazy):

![image](https://github.com/rachartier/tiny-devicons-auto-colors.nvim/assets/16181067/2774e000-0c3d-43de-8ac2-126bc2dc3042)

Thank you, and sorry about the non-issue :bow:

**Comment by rachartier** [comment]
Good to hear!

I see that you do a `table.insert`. I think you can directly do `require("...").setup({ colors = color_map })` !

Have a nice day
