### ISSUE TITLE
Question on troubleshooting a colorscheme

### ISSUE THREAD

**Issue by ColinKennedy** [rachartier/tiny-devicons-auto-colors.nvim#10]
First of all, thank your for this nice plugin. It makes icons "mesh" well with colorschemes :)

My current colorscheme looks like this

![image](https://github.com/rachartier/tiny-devicons-auto-colors.nvim/assets/10103049/b981f823-2411-4a7e-907a-41d74ad6736d)

And afterwards looks like this

![image](https://github.com/rachartier/tiny-devicons-auto-colors.nvim/assets/10103049/631d70f9-47da-41c3-a963-bbd72d6efc7d)

It's an overall improvement but markdown, which was mostly-white, is now blue. The data for blue comes from the colorscheme's ` custom_hl.get_custom_colors | get_hl("Question")` code. I noticed a couple other off-white colors ended up skewing blue for the same reason. Since there's multiple means of solving the color issue (e.g. a custom color palette or by changing factors), I was wondering how would you recommend solving this one color case without touching too many of the other colors (the rest of the colors look great as they are and I'd like to keep them)

**Comment by rachartier** [comment]
Hello!

One option could be to tweaks some factors:
```lua
    factors = {
        lightness = 1.75, -- Adjust the lightness factor.
        chroma = 1,       -- Adjust the chroma factor.
        hue = 1.25, 	  -- Adjust the hue factor.
    },
```
`chroma` do not really need to be modified for your needs (I think...). But `lightness` and `hue` can be good candidates. Maybe by increasing lightness to 2 ?

It is quite hard to find a good balance between all colorschemes, so I opted for these values, but you could easily modify it to suit your needs.

A second option, like you said, could be to create your own colors table, so that you can add only the colors you want.
Keep in mind that really close colors is hard to differentiate for the algorithm !

The best option for you, I think, is to ignore markdown. You could do:
```lua
    ignore = {
        "markdown"
    }
```
So that it keeps its original color.
And you could manually set the highlight for markdown like so:
```lua
require("nvim-web-devicons").set_icon {
      ["markdown"] = {
        icon = "",
        color = "#dddddd", -- replace by your color
        cterm_color = "253",
        name = "Markdown",
      },
}

```

I hope it answer your question !
